version: '3'

services:
  api:
    build:
      context: .
    container_name: api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    env_file: .env.docker
    command: npm run docker
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
