version: '3'

services:
  api:
    build:
      context: .
    container_name: api
    restart: unless-stopped
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - ./:/app
    env_file: .env
    command: npm run start
